  AWSTemplateFormatVersion: "2010-09-09"
  Parameters:
    HostedZoneId: 
      Type: AWS::Route53::HostedZone::Id
      Description: Select a zone
    DomainName:
      Type: String
      Description: The Name value to use in the record set
  Resources: 
    DKIMCNameRecord1:
      Type: AWS::Route53::RecordSet
      Properties:
        HostedZoneId: !Ref HostedZoneId
        Name: !Sub fm1._domainkey.${DomainName}
        Type: CNAME
        TTL: '3600'
        ResourceRecords:
        - !Sub 'fm1.${DomainName}.dkim.fmhosted.com'
    DKIMCNameRecord2:
      Type: AWS::Route53::RecordSet
      Properties:
        HostedZoneId: !Ref HostedZoneId
        Name: !Sub fm2._domainkey.${DomainName}
        Type: CNAME
        TTL: '3600'
        ResourceRecords:
        - !Sub 'fm2.${DomainName}.dkim.fmhosted.com'
    DKIMCNameRecord3:
      Type: AWS::Route53::RecordSet
      Properties:
        HostedZoneId: !Ref HostedZoneId
        Name: !Sub fm3._domainkey.${DomainName}
        Type: CNAME
        TTL: '3600'
        ResourceRecords:
        - !Sub 'fm3.${DomainName}.dkim.fmhosted.com'
    MXRecord:
      Type: AWS::Route53::RecordSet
      Properties:
        HostedZoneId: !Ref HostedZoneId
        Name: !Ref DomainName
        Type: MX
        TTL: '3600'
        ResourceRecords:
        - '10 in1-smtp.messagingengine.com'
        - '20 in2-smtp.messagingengine.com'
    MXRecordSubdomains:
      Type: AWS::Route53::RecordSet
      Properties:
        HostedZoneId: !Ref HostedZoneId
        Name: !Sub '*.${DomainName}'
        Type: MX
        TTL: '3600'
        ResourceRecords:
        - '10 in1-smtp.messagingengine.com'
        - '20 in2-smtp.messagingengine.com'
    WebMailRecord:
      Type: AWS::Route53::RecordSet
      Properties:
        HostedZoneId: !Ref HostedZoneId
        Name: !Sub 'mail.${DomainName}'
        Type: A
        TTL: '3600'
        ResourceRecords:
        - '66.111.4.147'
        - '66.111.4.148'
    SPFRecord:
      Type: AWS::Route53::RecordSet
      Properties:
        HostedZoneId: !Ref HostedZoneId
        Name: !Ref DomainName
        Type: TXT
        TTL: '3600'
        ResourceRecords:
        - '"v=spf1 include:spf.messagingengine.com ?all"'
    ClientEmailDiscovery1:
      Type: AWS::Route53::RecordSet
      Properties:
        HostedZoneId: !Ref HostedZoneId
        Name: !Sub '_submission._tcp.${DomainName}'
        Type: SRV
        TTL: '3600'
        ResourceRecords:
        - '0 1 587 smtp.fastmail.com'
    ClientEmailDiscovery2:
      Type: AWS::Route53::RecordSet
      Properties:
        HostedZoneId: !Ref HostedZoneId
        Name: !Sub '_imap._tcp.${DomainName}'
        Type: SRV
        TTL: '3600'
        ResourceRecords:
        - '0 0 0 .'
    ClientEmailDiscovery3:
      Type: AWS::Route53::RecordSet
      Properties:
        HostedZoneId: !Ref HostedZoneId
        Name: !Sub '_imaps._tcp.${DomainName}'
        Type: SRV
        TTL: '3600'
        ResourceRecords:
        - '0 1 993 imap.fastmail.com'
    ClientEmailDiscovery4:
      Type: AWS::Route53::RecordSet
      Properties:
        HostedZoneId: !Ref HostedZoneId
        Name: !Sub '_pop3._tcp.${DomainName}'
        Type: SRV
        TTL: '3600'
        ResourceRecords:
        - '0 0 0 .'
    ClientEmailDiscovery5:
      Type: AWS::Route53::RecordSet
      Properties:
        HostedZoneId: !Ref HostedZoneId
        Name: !Sub '_pop3s._tcp.${DomainName}'
        Type: SRV
        TTL: '3600'
        ResourceRecords:
        - '10 1 995 pop.fastmail.com'
    ClientCardDAVDiscovery1:
      Type: AWS::Route53::RecordSet
      Properties:
        HostedZoneId: !Ref HostedZoneId
        Name: !Sub '_carddav._tcp.${DomainName}'
        Type: SRV
        TTL: '3600'
        ResourceRecords:
        - '0 0 0 .'
    ClientCardDAVDiscovery2:
      Type: AWS::Route53::RecordSet
      Properties:
        HostedZoneId: !Ref HostedZoneId
        Name: !Sub '_carddavs._tcp.${DomainName}'
        Type: SRV
        TTL: '3600'
        ResourceRecords:
        - '0 1 443 carddav.fastmail.com'
    ClientCalDAVDiscovery1:
      Type: AWS::Route53::RecordSet
      Properties:
        HostedZoneId: !Ref HostedZoneId
        Name: !Sub '_caldav._tcp.${DomainName}'
        Type: SRV
        TTL: '3600'
        ResourceRecords:
        - '0 0 0 .'
    ClientCalDAVDiscovery2:
      Type: AWS::Route53::RecordSet
      Properties:
        HostedZoneId: !Ref HostedZoneId
        Name: !Sub '_caldavs._tcp.${DomainName}'
        Type: SRV
        TTL: '3600'
        ResourceRecords:
        - '0 1 443 caldav.fastmail.com'