  AWSTemplateFormatVersion: "2010-09-09"
  
  Description: Create DNS records for FastMail
  
  Parameters:
    ZoneId: 
      Type: AWS::Route53::HostedZone::Id
      Description: Enter a Route 53 ZoneId to add FastMail records to
  
    DomainName: 
      Type: String
      Description: Enter domain name to use for the DNS records

  Resources: 
    DKIMCNameRecord1:
      Type: AWS::Route53::RecordSet
      Properties:
        HostedZoneId: !Ref ZoneId
        Name: !Join [ ., [ 'fm1._domainkey', !Ref DomainName]] 
        Type: CNAME
        TTL: '3600'
        ResourceRecords:
        - !Join [ ., [ 'fm1', !Ref DomainName, 'dkim.fmhosted.com']] 

    DKIMCNameRecord2:
      Type: AWS::Route53::RecordSet
      Properties:
        HostedZoneId: !Ref ZoneId
        Name: !Join [ ., [ 'fm2._domainkey', !Ref DomainName]] 
        Type: CNAME
        TTL: '3600'
        ResourceRecords:
        - !Join [ ., [ 'fm2', !Ref DomainName, 'dkim.fmhosted.com']] 

    DKIMCNameRecord3:
      Type: AWS::Route53::RecordSet
      Properties:
        HostedZoneId: !Ref ZoneId
        Name: !Join [ ., [ 'fm3._domainkey', !Ref DomainName]] 
        Type: CNAME
        TTL: '3600'
        ResourceRecords:
        - !Join [ ., [ 'fm3', !Ref DomainName, 'dkim.fmhosted.com']] 

    MXRecord:
      Type: AWS::Route53::RecordSet
      Properties:
        HostedZoneId: !Ref ZoneId
        Name: !Ref DomainName
        Type: MX
        TTL: '3600'
        ResourceRecords:
        - '10 in1-smtp.messagingengine.com'
        - '20 in2-smtp.messagingengine.com'

    MXRecordSubdomains:
      Type: AWS::Route53::RecordSet
      Properties:
        HostedZoneId: !Ref ZoneId
        Name: !Join [ ., [ '*', !Ref DomainName]] 
        Type: MX
        TTL: '3600'
        ResourceRecords:
        - '10 in1-smtp.messagingengine.com'
        - '20 in2-smtp.messagingengine.com'

    WebMailRecord:
      Type: AWS::Route53::RecordSet
      Properties:
        HostedZoneId: !Ref ZoneId
        Name: !Join [ ., [ 'mail', !Ref DomainName]] 
        Type: A
        TTL: '3600'
        ResourceRecords:
        - '66.111.4.147'
        - '66.111.4.148'

    SPFRecord:
      Type: AWS::Route53::RecordSet
      Properties:
        HostedZoneId: !Ref ZoneId
        Name: !Ref DomainName
        Type: TXT
        TTL: '3600'
        ResourceRecords:
        - '"v=spf1 include:spf.messagingengine.com ?all"'

    ClientEmailDiscovery1:
      Type: AWS::Route53::RecordSet
      Properties:
        HostedZoneId: !Ref ZoneId
        Name: !Join [ ., [ '_submission._tcp', !Ref DomainName]] 
        Type: SRV
        TTL: '3600'
        ResourceRecords:
        - '0 1 587 smtp.fastmail.com'

    ClientEmailDiscovery2:
      Type: AWS::Route53::RecordSet
      Properties:
        HostedZoneId: !Ref ZoneId
        Name: !Join [ ., [ '_imap._tcp', !Ref DomainName]] 
        Type: SRV
        TTL: '3600'
        ResourceRecords:
        - '0 0 0 .'

    ClientEmailDiscovery3:
      Type: AWS::Route53::RecordSet
      Properties:
        HostedZoneId: !Ref ZoneId
        Name: !Join [ ., [ '_imaps._tcp', !Ref DomainName]] 
        Type: SRV
        TTL: '3600'
        ResourceRecords:
        - '0 1 993 imap.fastmail.com'

    ClientEmailDiscovery4:
      Type: AWS::Route53::RecordSet
      Properties:
        HostedZoneId: !Ref ZoneId
        Name: !Join [ ., [ '_pop3._tcp', !Ref DomainName]] 
        Type: SRV
        TTL: '3600'
        ResourceRecords:
        - '0 0 0 .'

    ClientEmailDiscovery5:
      Type: AWS::Route53::RecordSet
      Properties:
        HostedZoneId: !Ref ZoneId
        Name: !Join [ ., [ '_pop3s._tcp', !Ref DomainName]] 
        Type: SRV
        TTL: '3600'
        ResourceRecords:
        - '10 1 995 pop.fastmail.com'
        
    ClientCardDAVDiscovery1:
      Type: AWS::Route53::RecordSet
      Properties:
        HostedZoneId: !Ref ZoneId
        Name: !Join [ ., [ '_carddav._tcp', !Ref DomainName]] 
        Type: SRV
        TTL: '3600'
        ResourceRecords:
        - '0 0 0 .'

    ClientCardDAVDiscovery2:
      Type: AWS::Route53::RecordSet
      Properties:
        HostedZoneId: !Ref ZoneId
        Name: !Join [ ., [ '_carddavs._tcp', !Ref DomainName]]
        Type: SRV
        TTL: '3600'
        ResourceRecords:
        - '0 1 443 carddav.fastmail.com'

    ClientCalDAVDiscovery1:
      Type: AWS::Route53::RecordSet
      Properties:
        HostedZoneId: !Ref ZoneId
        Name: !Join [ ., [ '_caldav._tcp', !Ref DomainName]]
        Type: SRV
        TTL: '3600'
        ResourceRecords:
        - '0 0 0 .'
        
    ClientCalDAVDiscovery2:
      Type: AWS::Route53::RecordSet
      Properties:
        HostedZoneId: !Ref ZoneId
        Name: !Join [ ., [ '_caldavs._tcp', !Ref DomainName]]
        Type: SRV
        TTL: '3600'
        ResourceRecords:
        - '0 1 443 caldav.fastmail.com'